### PR TITLE
Python 101 added

### PR DESCRIPTION
**Pull request by realslimshanky**

### CODE REVIEW

**Comment by shashankaryan** [comment]
I think you should go for both python 3.x and 2.x.

**Comment by juggernaut451** [comment]
create python101 a new file

**Comment by realslimshanky** [comment]
@shashankaryan the course map I've added is not language specific and there's no need to learn 2.x separately. One should learn any 3.x and write in it. When in need he/she may refer to the python documentation and look up for some of the 2.x code.

**Comment by juggernaut451** [comment]
@realslimshanky resolve conflicts

**Comment by realslimshanky** [comment]
This resolves #10

**Pull request merged**
